Sprint1
ClevertecFrontendLab/sprint1-makrenka pull request #1
Opened 2023-02-01 07:00 UTC by makrenka

2023-02-01 07:03 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675235021/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675235021/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675235021/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675235021/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675235021/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675235021/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675235021/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675235021/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675235021/content-window.png)

2023-02-01 07:23 UTC, klichkovskiy requested changes

2023-02-01 07:23 UTC, klichkovskiy commented on src/components/molecules/breadcrump/breadcrump.tsx
> +                                <HandySvg
![image](https://user-images.githubusercontent.com/62481116/215977016-e7d47534-a044-49a5-82ba-cf5a98206b18.png)
Сделай по макету

2023-02-01 07:23 UTC, klichkovskiy commented on src/components/organisms/main-page-content/main-page-content.tsx
> +            <div className="main-page__content" data-test-id='main-page-content-tiles'>
промапай это все

2023-02-01 07:23 UTC, klichkovskiy commented on src/components/organisms/main-page-list-content/main-page-list-content.tsx
> +            <div className="main-page__list-content" data-test-id='main-page-content-list'>
Это очень плохая практика. Если не знаешь как сделать - оставляй.

2023-02-01 07:23 UTC, klichkovskiy commented on src/components/organisms/search-bar/search-bar.tsx
> +        return (
![image](https://user-images.githubusercontent.com/62481116/215977441-89616ae0-c554-4558-911f-34e7f1a1108f.png)
Исчезло. Почини

2023-02-01 07:23 UTC, klichkovskiy commented on src/components/organisms/search-bar/search-bar.tsx
> +                        <select name="select-search" id="books-select" className='search-bar__select'>
![image](https://user-images.githubusercontent.com/62481116/215977607-2904619d-69fa-4525-b190-24eb789b128b.png)
Это просто кнопка. Сделай ее по макету

2023-02-01 11:02 UTC, makrenka commented on src/components/molecules/breadcrump/breadcrump.tsx
> +                                <HandySvg
![Снимок экрана 2023-02-01 135524](https://user-images.githubusercontent.com/106319116/216024031-2b02825a-59db-468d-bea6-26cb83b18f1b.png)
У меня работает. Я использовал Handy SVG для загрузки svg, его устанавливать в пакет надо. Поэтому и кнопки не показывает. Надо исправлять?

2023-02-01 11:03 UTC, makrenka commented on src/components/organisms/main-page-list-content/main-page-list-content.tsx
> +            <div className="main-page__list-content" data-test-id='main-page-content-list'>
Знаю, исправлю, думал не усложнять на этом этапе, промапить, когда буду с сервера данные получать

2023-02-01 11:06 UTC, makrenka commented on src/components/organisms/search-bar/search-bar.tsx
> +        return (
![Снимок экрана 2023-02-01 135524](https://user-images.githubusercontent.com/106319116/216026098-1cbdc702-7d06-4b69-922a-30fdbd2dbfa2.png)
Работает - Handy SVG

2023-02-01 19:55 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 3.
Количество непройденных тестов: 3.
***
**Test width 1440px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675281353/Test%20width%201440px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 320px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675281353/Test%20width%20320px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 768px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675281353/Test%20width%20768px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)

2023-02-01 20:13 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 3.
Количество непройденных тестов: 3.
***
**Test width 1440px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675282394/Test%20width%201440px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 320px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675282394/Test%20width%20320px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 768px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675282394/Test%20width%20768px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)

2023-02-01 20:27 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 3.
Количество непройденных тестов: 3.
***
**Test width 1440px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675283236/Test%20width%201440px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 320px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675283236/Test%20width%20320px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 768px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675283236/Test%20width%20768px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)

2023-02-01 20:32 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 3.
Количество непройденных тестов: 3.
***
**Test width 1440px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675283568/Test%20width%201440px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 320px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675283568/Test%20width%20320px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 768px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675283568/Test%20width%20768px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)

2023-02-01 20:43 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 3.
Количество непройденных тестов: 3.
***
**Test width 1440px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675284201/Test%20width%201440px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 320px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675284201/Test%20width%20320px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)
***
**Test width 768px -- test layout content view -- before each hook (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675284201/Test%20width%20768px%20--%20test%20layout%20content%20view%20--%20before%20each%20hook%20(failed).png)

2023-02-01 21:00 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 0%.
Общее количество тестов: 6.
Количество непройденных тестов: 6.
***
**Test width 1440px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675285232/Test%20width%201440px%20--%20test%20layout%20book-page%20(failed).png)
***
**Test width 1440px -- test layout content view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675285232/Test%20width%201440px%20--%20test%20layout%20content%20view%20(failed).png)
***
**Test width 320px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675285232/Test%20width%20320px%20--%20test%20layout%20book-page%20(failed).png)
***
**Test width 320px -- test layout content view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675285232/Test%20width%20320px%20--%20test%20layout%20content%20view%20(failed).png)
***
**Test width 768px -- test layout book-page (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675285232/Test%20width%20768px%20--%20test%20layout%20book-page%20(failed).png)
***
**Test width 768px -- test layout content view (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/makrenka/1675285232/Test%20width%20768px%20--%20test%20layout%20content%20view%20(failed).png)

2023-02-02 06:38 UTC, klichkovskiy approved these changes

2023-02-02 06:43 UTC, merged